DROP TABLE IF EXISTS `domain`;
CREATE TABLE IF NOT EXISTS `domain` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `owner` bigint(20) unsigned NOT NULL,
  `path` varchar(255) NOT NULL,
  `level` int(10) NOT NULL DEFAULT '0',
  `child_count` int(10) NOT NULL DEFAULT '0',
  `next_child_seq` bigint(20) unsigned NOT NULL DEFAULT '1',
  `removed` datetime DEFAULT NULL,
  `state` char(32) NOT NULL DEFAULT 'Active',
  `network_domain` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL DEFAULT 'Normal',
  PRIMARY KEY (`id`),
  UNIQUE KEY `parent` (`parent`,`name`,`removed`),
  UNIQUE KEY `uc_domain__uuid` (`uuid`),
  KEY `i_domain__path` (`path`),
  KEY `i_domain__removed` (`removed`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `vm_instance`;
CREATE TABLE IF NOT EXISTS `vm_instance` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `instance_name` varchar(255) NOT NULL,
  `state` varchar(32) NOT NULL,
  `vm_template_id` bigint(20) unsigned DEFAULT NULL,
  `guest_os_id` bigint(20) unsigned NOT NULL,
  `private_mac_address` varchar(17) DEFAULT NULL,
  `private_ip_address` char(40) DEFAULT NULL,
  `pod_id` bigint(20) unsigned DEFAULT NULL,
  `data_center_id` bigint(20) unsigned NOT NULL,
  `host_id` bigint(20) unsigned DEFAULT NULL,
  `last_host_id` bigint(20) unsigned DEFAULT NULL,
  `proxy_id` bigint(20) unsigned DEFAULT NULL,
  `proxy_assign_time` datetime DEFAULT NULL,
  `vnc_password` varchar(255) NOT NULL,
  `ha_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `limit_cpu_use` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `update_count` bigint(20) unsigned NOT NULL DEFAULT '0',
  `update_time` datetime DEFAULT NULL,
  `created` datetime NOT NULL,
  `removed` datetime DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `vm_type` varchar(32) NOT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `domain_id` bigint(20) unsigned NOT NULL,
  `service_offering_id` bigint(20) unsigned NOT NULL,
  `reservation_id` char(40) DEFAULT NULL,
  `hypervisor_type` char(32) DEFAULT NULL,
  `disk_offering_id` bigint(20) unsigned DEFAULT NULL,
  `owner` varchar(255) DEFAULT NULL,
  `host_name` varchar(255) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `desired_state` varchar(32) DEFAULT NULL,
  `dynamically_scalable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `display_vm` tinyint(1) NOT NULL DEFAULT '1',
  `power_state` varchar(74) DEFAULT 'PowerUnknown',
  `power_state_update_time` datetime DEFAULT NULL,
  `power_state_update_count` int(11) DEFAULT '0',
  `power_host` bigint(20) unsigned DEFAULT NULL,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_vm_instance_uuid` (`uuid`),
  KEY `i_vm_instance__removed` (`removed`),
  KEY `i_vm_instance__type` (`type`),
  KEY `i_vm_instance__pod_id` (`pod_id`),
  KEY `i_vm_instance__update_time` (`update_time`),
  KEY `i_vm_instance__update_count` (`update_count`),
  KEY `i_vm_instance__state` (`state`),
  KEY `i_vm_instance__data_center_id` (`data_center_id`),
  KEY `fk_vm_instance__host_id` (`host_id`),
  KEY `fk_vm_instance__last_host_id` (`last_host_id`),
  KEY `i_vm_instance__template_id` (`vm_template_id`),
  KEY `fk_vm_instance__account_id` (`account_id`),
  KEY `fk_vm_instance__service_offering_id` (`service_offering_id`),
  KEY `fk_vm_instance__power_host` (`power_host`),
  KEY `i_vm_instance__instance_name` (`instance_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `vm_template`;
CREATE TABLE `vm_template` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `unique_name` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `public` int(1) unsigned NOT NULL,
  `featured` int(1) unsigned NOT NULL,
  `type` varchar(32) DEFAULT NULL,
  `hvm` int(1) unsigned NOT NULL,
  `bits` int(6) unsigned NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `format` varchar(32) NOT NULL,
  `created` datetime NOT NULL,
  `removed` datetime DEFAULT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `checksum` varchar(255) DEFAULT NULL,
  `display_text` varchar(4096) DEFAULT NULL,
  `enable_password` int(1) unsigned NOT NULL DEFAULT '1',
  `enable_sshkey` int(1) unsigned NOT NULL DEFAULT '0',
  `guest_os_id` bigint(20) unsigned NOT NULL,
  `bootable` int(1) unsigned NOT NULL DEFAULT '1',
  `prepopulate` int(1) unsigned NOT NULL DEFAULT '0',
  `cross_zones` int(1) unsigned NOT NULL DEFAULT '0',
  `extractable` int(1) unsigned NOT NULL DEFAULT '0',
  `hypervisor_type` varchar(32) DEFAULT NULL,
  `source_template_id` bigint(20) unsigned DEFAULT NULL,
  `template_tag` varchar(255) DEFAULT NULL,
  `sort_key` int(32) NOT NULL DEFAULT '0',
  `size` bigint(20) unsigned DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `update_count` bigint(20) unsigned DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `dynamically_scalable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_vm_template__uuid` (`uuid`),
  KEY `i_vm_template__removed` (`removed`),
  KEY `i_vm_template__public` (`public`)
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `volumes`;
CREATE TABLE IF NOT EXISTS `volumes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `domain_id` bigint(20) unsigned NOT NULL,
  `pool_id` bigint(20) unsigned DEFAULT NULL,
  `last_pool_id` bigint(20) unsigned DEFAULT NULL,
  `instance_id` bigint(20) unsigned DEFAULT NULL,
  `device_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `size` bigint(20) unsigned NOT NULL,
  `folder` varchar(255) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  `pod_id` bigint(20) unsigned DEFAULT NULL,
  `data_center_id` bigint(20) unsigned NOT NULL,
  `iscsi_name` varchar(255) DEFAULT NULL,
  `host_ip` char(40) DEFAULT NULL,
  `volume_type` varchar(64) NOT NULL,
  `pool_type` varchar(64) DEFAULT NULL,
  `disk_offering_id` bigint(20) unsigned NOT NULL,
  `template_id` bigint(20) unsigned DEFAULT NULL,
  `first_snapshot_backup_uuid` varchar(255) DEFAULT NULL,
  `recreatable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `created` datetime DEFAULT NULL,
  `attached` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `removed` datetime DEFAULT NULL,
  `state` varchar(32) DEFAULT NULL,
  `chain_info` text,
  `update_count` bigint(20) unsigned NOT NULL DEFAULT '0',
  `disk_type` varchar(255) DEFAULT NULL,
  `vm_snapshot_chain_size` bigint(20) unsigned DEFAULT NULL,
  `iso_id` bigint(20) unsigned DEFAULT NULL,
  `display_volume` tinyint(1) NOT NULL DEFAULT '1',
  `format` varchar(255) DEFAULT NULL,
  `min_iops` bigint(20) unsigned DEFAULT NULL,
  `max_iops` bigint(20) unsigned DEFAULT NULL,
  `hv_ss_reserve` int(32) unsigned DEFAULT NULL,
  `provisioning_type` varchar(32) NOT NULL DEFAULT 'thin',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_volumes__uuid` (`uuid`),
  KEY `i_volumes__removed` (`removed`),
  KEY `i_volumes__pod_id` (`pod_id`),
  KEY `i_volumes__data_center_id` (`data_center_id`),
  KEY `i_volumes__account_id` (`account_id`),
  KEY `i_volumes__pool_id` (`pool_id`),
  KEY `i_volumes__last_pool_id` (`last_pool_id`),
  KEY `i_volumes__instance_id` (`instance_id`),
  KEY `i_volumes__state` (`state`),
  KEY `i_volumes__update_count` (`update_count`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_offering`;
CREATE TABLE IF NOT EXISTS `service_offering` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cpu` int(10) unsigned DEFAULT NULL,
  `speed` int(10) unsigned DEFAULT NULL,
  `ram_size` bigint(20) unsigned DEFAULT NULL,
  `nw_rate` smallint(5) unsigned DEFAULT '200',
  `mc_rate` smallint(5) unsigned DEFAULT '10',
  `ha_enabled` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `limit_cpu_use` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `host_tag` varchar(255) DEFAULT NULL,
  `default_use` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vm_type` varchar(32) DEFAULT NULL,
  `sort_key` int(32) NOT NULL DEFAULT '0',
  `is_volatile` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `deployment_planner` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user_ip_address`;
CREATE TABLE IF NOT EXISTS `user_ip_address` (
 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(40) DEFAULT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `domain_id` bigint(20) unsigned DEFAULT NULL,
  `public_ip_address` char(40) NOT NULL,
  `data_center_id` bigint(20) unsigned NOT NULL,
  `source_nat` int(1) unsigned NOT NULL DEFAULT '0',
  `allocated` datetime DEFAULT NULL,
  `vlan_db_id` bigint(20) unsigned NOT NULL,
  `one_to_one_nat` int(1) unsigned NOT NULL DEFAULT '0',
  `vm_id` bigint(20) unsigned DEFAULT NULL,
  `state` char(32) NOT NULL DEFAULT 'Free',
  `mac_address` bigint(20) unsigned NOT NULL,
  `source_network_id` bigint(20) unsigned NOT NULL,
  `network_id` bigint(20) unsigned DEFAULT NULL,
  `physical_network_id` bigint(20) unsigned NOT NULL,
  `ip_acl_id` bigint(20) unsigned NOT NULL,
  `is_system` int(1) unsigned NOT NULL DEFAULT '0',
  `vpc_id` bigint(20) unsigned DEFAULT NULL,
  `dnat_vmip` varchar(40) DEFAULT NULL,
  `is_portable` int(1) unsigned NOT NULL DEFAULT '0',
  `display` tinyint(1) NOT NULL DEFAULT '1',
  `removed` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_user_ip_address__uuid` (`uuid`),
  UNIQUE KEY `public_ip_address` (`public_ip_address`,`source_network_id`,`removed`),
  KEY `fk_user_ip_address__source_network_id` (`source_network_id`),
  KEY `fk_user_ip_address__network_id` (`network_id`),
  KEY `fk_user_ip_address__account_id` (`account_id`),
  KEY `fk_user_ip_address__vm_id` (`vm_id`),
  KEY `fk_user_ip_address__vlan_db_id` (`vlan_db_id`),
  KEY `fk_user_ip_address__data_center_id` (`data_center_id`),
  KEY `fk_user_ip_address__physical_network_id` (`physical_network_id`),
  KEY `fk_user_ip_address__vpc_id` (`vpc_id`),
  KEY `i_user_ip_address__allocated` (`allocated`),
  KEY `i_user_ip_address__source_nat` (`source_nat`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `networks`;
CREATE TABLE IF NOT EXISTS `networks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `display_text` varchar(255) DEFAULT NULL,
  `traffic_type` varchar(32) NOT NULL,
  `broadcast_domain_type` varchar(32) NOT NULL,
  `broadcast_uri` varchar(255) DEFAULT NULL,
  `gateway` varchar(15) DEFAULT NULL,
  `cidr` varchar(18) DEFAULT NULL,
  `mode` varchar(32) DEFAULT NULL,
  `network_offering_id` bigint(20) unsigned NOT NULL,
  `physical_network_id` bigint(20) unsigned DEFAULT NULL,
  `data_center_id` bigint(20) unsigned NOT NULL,
  `guru_name` varchar(255) NOT NULL,
  `state` varchar(32) NOT NULL,
  `related` bigint(20) unsigned NOT NULL,
  `domain_id` bigint(20) unsigned NOT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `dns1` varchar(255) DEFAULT NULL,
  `dns2` varchar(255) DEFAULT NULL,
  `guru_data` varchar(1024) DEFAULT NULL,
  `set_fields` bigint(20) unsigned NOT NULL DEFAULT '0',
  `acl_type` varchar(15) DEFAULT NULL,
  `network_domain` varchar(255) DEFAULT NULL,
  `reservation_id` char(40) DEFAULT NULL,
  `guest_type` char(32) DEFAULT NULL,
  `restart_required` int(1) unsigned NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `removed` datetime DEFAULT NULL,
  `specify_ip_ranges` int(1) unsigned NOT NULL DEFAULT '0',
  `vpc_id` bigint(20) unsigned DEFAULT NULL,
  `ip6_gateway` varchar(50) DEFAULT NULL,
  `ip6_cidr` varchar(50) DEFAULT NULL,
  `network_cidr` varchar(18) DEFAULT NULL,
  `display_network` tinyint(1) NOT NULL DEFAULT '1',
  `network_acl_id` bigint(20) unsigned DEFAULT NULL,
  `streched_l2` tinyint(1) DEFAULT '0',
  `redundant` tinyint(1) DEFAULT '0',
  `ip_exclusion_list` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_networks__uuid` (`uuid`),
  KEY `fk_networks__network_offering_id` (`network_offering_id`),
  KEY `fk_networks__data_center_id` (`data_center_id`),
  KEY `fk_networks__related` (`related`),
  KEY `fk_networks__account_id` (`account_id`),
  KEY `fk_networks__domain_id` (`domain_id`),
  KEY `fk_networks__vpc_id` (`vpc_id`),
  KEY `i_networks__removed` (`removed`)
) ENGINE=InnoDB AUTO_INCREMENT=207 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `vpc`;
CREATE TABLE IF NOT EXISTS `vpc` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(40) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `display_text` varchar(255) DEFAULT NULL,
  `cidr` varchar(18) DEFAULT NULL,
  `vpc_offering_id` bigint(20) unsigned NOT NULL,
  `zone_id` bigint(20) unsigned NOT NULL,
  `state` varchar(32) NOT NULL,
  `domain_id` bigint(20) unsigned NOT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `network_domain` varchar(255) DEFAULT NULL,
  `removed` datetime DEFAULT NULL,
  `created` datetime NOT NULL,
  `restart_required` int(1) unsigned NOT NULL DEFAULT '0',
  `display` tinyint(1) NOT NULL DEFAULT '1',
  `uses_distributed_router` tinyint(1) DEFAULT '0',
  `region_level_vpc` tinyint(1) DEFAULT '0',
  `redundant` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `i_vpc__removed` (`removed`),
  KEY `fk_vpc__zone_id` (`zone_id`),
  KEY `fk_vpc__vpc_offering_id` (`vpc_offering_id`),
  KEY `fk_vpc__account_id` (`account_id`),
  KEY `fk_vpc__domain_id` (`domain_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
