DROP TABLE IF EXISTS `domain`;
CREATE TABLE IF NOT EXISTS `domain` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `owner` bigint(20) unsigned NOT NULL,
  `path` varchar(255) NOT NULL,
  `level` int(10) NOT NULL DEFAULT '0',
  `child_count` int(10) NOT NULL DEFAULT '0',
  `next_child_seq` bigint(20) unsigned NOT NULL DEFAULT '1',
  `removed` datetime DEFAULT NULL,
  `state` char(32) NOT NULL DEFAULT 'Active',
  `network_domain` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL DEFAULT 'Normal',
  PRIMARY KEY (`id`),
  UNIQUE KEY `parent` (`parent`,`name`,`removed`),
  UNIQUE KEY `uc_domain__uuid` (`uuid`),
  KEY `i_domain__path` (`path`),
  KEY `i_domain__removed` (`removed`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `vm_instance`;
CREATE TABLE IF NOT EXISTS `vm_instance` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `instance_name` varchar(255) NOT NULL,
  `state` varchar(32) NOT NULL,
  `vm_template_id` bigint(20) unsigned DEFAULT NULL,
  `guest_os_id` bigint(20) unsigned NOT NULL,
  `private_mac_address` varchar(17) DEFAULT NULL,
  `private_ip_address` char(40) DEFAULT NULL,
  `pod_id` bigint(20) unsigned DEFAULT NULL,
  `data_center_id` bigint(20) unsigned NOT NULL,
  `host_id` bigint(20) unsigned DEFAULT NULL,
  `last_host_id` bigint(20) unsigned DEFAULT NULL,
  `proxy_id` bigint(20) unsigned DEFAULT NULL,
  `proxy_assign_time` datetime DEFAULT NULL,
  `vnc_password` varchar(255) NOT NULL,
  `ha_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `limit_cpu_use` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `update_count` bigint(20) unsigned NOT NULL DEFAULT '0',
  `update_time` datetime DEFAULT NULL,
  `created` datetime NOT NULL,
  `removed` datetime DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `vm_type` varchar(32) NOT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `domain_id` bigint(20) unsigned NOT NULL,
  `service_offering_id` bigint(20) unsigned NOT NULL,
  `reservation_id` char(40) DEFAULT NULL,
  `hypervisor_type` char(32) DEFAULT NULL,
  `disk_offering_id` bigint(20) unsigned DEFAULT NULL,
  `owner` varchar(255) DEFAULT NULL,
  `host_name` varchar(255) DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `desired_state` varchar(32) DEFAULT NULL,
  `dynamically_scalable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `display_vm` tinyint(1) NOT NULL DEFAULT '1',
  `power_state` varchar(74) DEFAULT 'PowerUnknown',
  `power_state_update_time` datetime DEFAULT NULL,
  `power_state_update_count` int(11) DEFAULT '0',
  `power_host` bigint(20) unsigned DEFAULT NULL,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_vm_instance_uuid` (`uuid`),
  KEY `i_vm_instance__removed` (`removed`),
  KEY `i_vm_instance__type` (`type`),
  KEY `i_vm_instance__pod_id` (`pod_id`),
  KEY `i_vm_instance__update_time` (`update_time`),
  KEY `i_vm_instance__update_count` (`update_count`),
  KEY `i_vm_instance__state` (`state`),
  KEY `i_vm_instance__data_center_id` (`data_center_id`),
  KEY `fk_vm_instance__host_id` (`host_id`),
  KEY `fk_vm_instance__last_host_id` (`last_host_id`),
  KEY `i_vm_instance__template_id` (`vm_template_id`),
  KEY `fk_vm_instance__account_id` (`account_id`),
  KEY `fk_vm_instance__service_offering_id` (`service_offering_id`),
  KEY `fk_vm_instance__power_host` (`power_host`),
  KEY `i_vm_instance__instance_name` (`instance_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `vm_template`;
CREATE TABLE `vm_template` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `unique_name` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `public` int(1) unsigned NOT NULL,
  `featured` int(1) unsigned NOT NULL,
  `type` varchar(32) DEFAULT NULL,
  `hvm` int(1) unsigned NOT NULL,
  `bits` int(6) unsigned NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `format` varchar(32) NOT NULL,
  `created` datetime NOT NULL,
  `removed` datetime DEFAULT NULL,
  `account_id` bigint(20) unsigned DEFAULT NULL,
  `checksum` varchar(255) DEFAULT NULL,
  `display_text` varchar(4096) DEFAULT NULL,
  `enable_password` int(1) unsigned NOT NULL DEFAULT '1',
  `enable_sshkey` int(1) unsigned NOT NULL DEFAULT '0',
  `guest_os_id` bigint(20) unsigned NOT NULL,
  `bootable` int(1) unsigned NOT NULL DEFAULT '1',
  `prepopulate` int(1) unsigned NOT NULL DEFAULT '0',
  `cross_zones` int(1) unsigned NOT NULL DEFAULT '0',
  `extractable` int(1) unsigned NOT NULL DEFAULT '0',
  `hypervisor_type` varchar(32) DEFAULT NULL,
  `source_template_id` bigint(20) unsigned DEFAULT NULL,
  `template_tag` varchar(255) DEFAULT NULL,
  `sort_key` int(32) NOT NULL DEFAULT '0',
  `size` bigint(20) unsigned DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `update_count` bigint(20) unsigned DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `dynamically_scalable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_vm_template__uuid` (`uuid`),
  KEY `i_vm_template__removed` (`removed`),
  KEY `i_vm_template__public` (`public`)
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8;
